"""
Unit tests for utils/waf_evasion.py
"""
import pytest
import httpx
from utils.waf_evasion import WAFEvasion, EvasionAction, WAFDetectionResult

def test_waf_evasion_profiles():
    # Valid profiles
    for profile in ["stealth", "aggressive", "bypass"]:
        evasion = WAFEvasion(profile=profile)
        assert evasion.profile == profile
        assert isinstance(evasion.config, dict)

    # Invalid profile
    with pytest.raises(ValueError, match="Unknown WAF evasion profile"):
        WAFEvasion(profile="unknown_profile")

def test_waf_detection_status_codes():
    evasion = WAFEvasion()
    
    # Non-blocking status code
    resp_ok = httpx.Response(status_code=200, content=b"OK")
    result = evasion.detect(resp_ok)
    assert result.detected is False
    assert result.confidence == 0.0

    # Blocking status code
    resp_block = httpx.Response(status_code=403, content=b"Forbidden")
    result = evasion.detect(resp_block)
    assert result.detected is True
    assert result.block_type == "status_code"
    assert result.confidence == 0.4

def test_waf_detection_headers():
    evasion = WAFEvasion()

    # Cloudflare header detection
    resp = httpx.Response(
        status_code=200,
        headers={"cf-ray": "1234567890abcdef", "server": "cloudflare"},
        content=b"OK"
    )
    result = evasion.detect(resp)
    assert result.detected is True
    assert result.vendor == "Cloudflare"
    assert result.block_type == "header"
    assert result.confidence > 0.4

def test_waf_detection_body():
    evasion = WAFEvasion()

    # ModSecurity body signature detection
    resp = httpx.Response(
        status_code=200,
        content=b"this error was generated by mod_security"
    )
    result = evasion.detect(resp)
    assert result.detected is True
    assert result.vendor == "ModSecurity"
    assert result.block_type == "body"

def test_recommend_action_escalation():
    evasion = WAFEvasion(profile="stealth")  # max_retries: 3

    # Successive blocks
    r_block = WAFDetectionResult(detected=True)

    # Block 1
    evasion._blocked_count = 1
    action = evasion.recommend_action(r_block)
    assert action == EvasionAction.ROTATE_UA

    # Block 2
    evasion._blocked_count = 2
    action = evasion.recommend_action(r_block)
    assert action == EvasionAction.ADD_DELAY

    # Block 3
    evasion._blocked_count = 3
    action = evasion.recommend_action(r_block)
    assert action == EvasionAction.CHANGE_ENCODING

    # Block 4 -> should abort because stealth max_retries is 3, and 4 > 3
    evasion._blocked_count = 4
    action = evasion.recommend_action(r_block)
    assert action == EvasionAction.ABORT

def test_get_evasion_headers():
    evasion = WAFEvasion(profile="bypass")
    headers = evasion.get_evasion_headers()
    assert "Accept" in headers
    assert "User-Agent" in headers
    assert headers["Cache-Control"] == "no-cache"
