"""
utils/waf_evasion.py — Adaptive WAF detection and evasion for ScopeX v2.

Detects WAF block signatures in HTTP responses and recommends evasion techniques.
Integrated into BaseScanner automatically through ctx.waf_evasion and
ctx.waf_evasion_profile, but can also be used standalone for explicit WAF
fingerprinting passes.
"""
from __future__ import annotations

import random
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Tuple

import httpx
from loguru import logger


# ---------------------------------------------------------------------------
# Evasion action enum
# ---------------------------------------------------------------------------


class EvasionAction(Enum):
    """Recommended action after a WAF block is detected."""

    NONE = "none"
    """No block detected — proceed normally."""

    ROTATE_UA = "rotate_ua"
    """Rotate the User-Agent string and retry."""

    ADD_DELAY = "add_delay"
    """Add a longer randomised delay before retrying."""

    CHANGE_ENCODING = "change_encoding"
    """Apply URL / unicode encoding variants to the payload."""

    FRAGMENT_REQUEST = "fragment_request"
    """Split the request across multiple partial requests (chunked)."""

    ABORT = "abort"
    """Abort scanning this target — block count exceeded retry budget."""


# ---------------------------------------------------------------------------
# WAF signature database
# ---------------------------------------------------------------------------

# Each signature entry: (header_name_or_None, value_fragment_or_None)
# - If header_name is not None: match against response header (case-insensitive)
# - If header_name is None and value_fragment is not None: match against body
_Sig = Tuple[Optional[str], Optional[str]]

WAF_SIGNATURES: Dict[str, List[_Sig]] = {
    "Cloudflare": [
        ("cf-ray", None),                         # any value → Cloudflare
        ("cf-cache-status", None),
        ("server", "cloudflare"),
        (None, "error 1020"),                     # body: access denied
        (None, "cloudflare ray id"),
        (None, "checking your browser before"),   # JS challenge page
    ],
    "AWS WAF": [
        ("x-amzn-requestid", None),
        ("x-amz-cf-id", None),
        ("x-amz-apigw-id", None),
        (None, "request blocked"),
        (None, "aws waf"),
    ],
    "ModSecurity": [
        (None, "modsecurity"),
        (None, "not acceptable!"),                # default ModSec 406 page
        ("server", "mod_security"),
        (None, "this error was generated by mod_security"),
    ],
    "Imperva / Incapsula": [
        ("x-iinfo", None),
        ("x-cdn", "incapsula"),
        (None, "incapsula incident id"),
        (None, "request unsuccessful"),
        (None, "powered by incapsula"),
    ],
    "Akamai": [
        ("x-check-cacheable", None),
        ("server", "akamaighost"),
        (None, "access denied"),
        (None, "reference #"),                    # Akamai error page pattern
    ],
    "Sucuri": [
        ("x-sucuri-id", None),
        ("x-sucuri-cache", None),
        (None, "sucuri website firewall"),
        (None, "access denied - sucuri"),
    ],
    "F5 BIG-IP ASM": [
        (None, "the requested url was rejected"),
        ("server", "bigip"),
        ("x-wa-info", None),
        (None, "your support id is"),
    ],
    "Barracuda WAF": [
        (None, "you have been blocked"),
        ("server", "barracuda"),
        (None, "barracuda networks"),
    ],
    "Fortinet FortiWeb": [
        (None, "fortiweb"),
        (None, "web page blocked!"),
        ("server", "fortiweb"),
        (None, "_sgi_server_error_"),
    ],
    "Wordfence": [
        (None, "generated by wordfence"),
        (None, "your access to this site has been limited"),
        (None, "wordfence"),
    ],
    "DenyAll": [
        (None, "denyall"),
        ("x-denyall-requestid", None),
    ],
    "Wallarm": [
        ("x-wallarm-node", None),
        (None, "wallarm"),
    ],
    "Radware AppWall": [
        (None, "unauthorized activity has been detected"),
        ("x-sl-compstate", None),
    ],
    "Reblaze": [
        ("x-reblaze-protection", None),
        ("server", "reblaze"),
    ],
    "NGINX ModSecurity": [
        ("server", "nginx"),
        (None, "error id:"),
        (None, "nginx/waf"),
    ],
}

# Status codes that commonly indicate a WAF block (not always WAF, but suspicious)
BLOCK_STATUS_CODES: frozenset = frozenset({403, 406, 429, 503, 999})


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------


@dataclass
class WAFDetectionResult:
    """Result returned by :meth:`WAFEvasion.detect`."""

    detected: bool = False
    """True if any WAF signature was matched."""

    vendor: Optional[str] = None
    """Name of the identified WAF vendor (``None`` if unknown)."""

    confidence: float = 0.0
    """Confidence level 0.0–1.0 (1.0 = multiple strong signatures matched)."""

    block_type: str = "none"
    """How the block was identified: ``'status_code'`` | ``'header'`` | ``'body'``."""

    matched_signatures: List[str] = field(default_factory=list)
    """Human-readable list of individual signatures that matched."""

    def __bool__(self) -> bool:
        return self.detected


# ---------------------------------------------------------------------------
# WAFEvasion class
# ---------------------------------------------------------------------------


class WAFEvasion:
    """
    Adaptive WAF detection and evasion helper for ScopeX v2.

    Detects WAF blocks from HTTP responses via signature matching and
    recommends evasion actions.  Tracks block frequency per instance to
    escalate evasion techniques progressively.

    Usage::

        waf = WAFEvasion(profile="stealth")
        result = waf.detect(response)
        if result:
            action = waf.recommend_action(result)
            evasion_headers = waf.get_evasion_headers()
    """

    PROFILES: Dict[str, Dict] = {
        "stealth": {
            "delay_range": (1.0, 3.0),
            "rotate_ua": True,
            "jitter": True,
            "encoding_variants": False,
            "max_retries": 3,
            "description": "Low-and-slow — maximises stealth at the cost of speed.",
        },
        "aggressive": {
            "delay_range": (0.1, 0.5),
            "rotate_ua": True,
            "jitter": False,
            "encoding_variants": True,
            "max_retries": 5,
            "description": "Fast enumeration with UA rotation and encoding tricks.",
        },
        "bypass": {
            "delay_range": (0.5, 1.5),
            "rotate_ua": True,
            "jitter": True,
            "encoding_variants": True,
            "chunked_encoding": True,
            "case_variation": True,
            "unicode_normalization": True,
            "max_retries": 5,
            "description": "Full bypass arsenal — tries every available technique.",
        },
    }

    def __init__(self, profile: str = "stealth") -> None:
        """
        Initialise WAFEvasion with a chosen profile.

        Args:
            profile: One of ``'stealth'``, ``'aggressive'``, or ``'bypass'``.

        Raises:
            ValueError: If an unknown profile name is provided.
        """
        if profile not in self.PROFILES:
            raise ValueError(
                f"Unknown WAF evasion profile: {profile!r}. "
                f"Valid profiles: {sorted(self.PROFILES)}"
            )
        self.profile = profile
        self.config: Dict = self.PROFILES[profile]
        self.log = logger.bind(scanner="WAFEvasion")
        self._blocked_count: int = 0
        self._successful_technique: Optional[str] = None
        self._detected_vendor: Optional[str] = None

    # ------------------------------------------------------------------
    # Core detection
    # ------------------------------------------------------------------

    def detect(self, response: httpx.Response) -> WAFDetectionResult:
        """
        Analyse an HTTP response for WAF block signatures.

        Checks:
        1. HTTP status code against known block codes
        2. Response headers against vendor-specific header signatures
        3. Response body against vendor-specific text patterns

        Args:
            response: The :class:`httpx.Response` to analyse.

        Returns:
            A :class:`WAFDetectionResult` describing what was found.
        """
        result = WAFDetectionResult()

        # Step 1: Status-code-based detection
        if response.status_code in BLOCK_STATUS_CODES:
            result.detected = True
            result.block_type = "status_code"
            result.confidence = 0.4
            result.matched_signatures.append(
                f"HTTP {response.status_code} (block status code)"
            )

        # Step 2: Normalise headers and body for matching
        resp_headers: Dict[str, str] = {
            k.lower(): v.lower() for k, v in response.headers.items()
        }
        try:
            resp_body: str = response.text.lower()
        except Exception:
            resp_body = ""

        # Step 3: Signature matching per vendor
        for vendor, signatures in WAF_SIGNATURES.items():
            vendor_matches: List[str] = []

            for sig in signatures:
                header_name, value_frag = sig

                if header_name is not None:
                    # Header-based signature
                    if header_name in resp_headers:
                        if value_frag is None or value_frag in resp_headers[header_name]:
                            vendor_matches.append(
                                f"header:{header_name}"
                                + (f"={value_frag!r}" if value_frag else "")
                            )
                else:
                    # Body-based signature
                    if value_frag and value_frag in resp_body:
                        vendor_matches.append(f"body:{value_frag!r}")

            if vendor_matches:
                confidence = min(
                    1.0,
                    len(vendor_matches) / max(len(signatures), 1) + 0.3,
                )
                if confidence > result.confidence:
                    result.detected = True
                    result.vendor = vendor
                    result.confidence = confidence
                    result.block_type = (
                        "header"
                        if any("header:" in m for m in vendor_matches)
                        else "body"
                    )
                result.matched_signatures.extend(
                    [f"{vendor}:{m}" for m in vendor_matches]
                )

        if result.detected:
            self._blocked_count += 1
            if result.vendor:
                self._detected_vendor = result.vendor
            self.log.warning(
                "WAF block detected",
                extra={
                    "vendor": result.vendor or "unknown",
                    "confidence": f"{result.confidence:.0%}",
                    "block_type": result.block_type,
                    "total_blocks": self._blocked_count,
                    "signatures": result.matched_signatures[:5],  # avoid log spam
                },
            )
        else:
            self.log.debug("No WAF block detected in response")

        return result

    # ------------------------------------------------------------------
    # Action recommendation
    # ------------------------------------------------------------------

    def recommend_action(self, result: WAFDetectionResult) -> EvasionAction:
        """
        Recommend an evasion action based on block history and detection result.

        The recommendation escalates with successive blocks:
          1st block  → :attr:`EvasionAction.ROTATE_UA`
          2nd block  → :attr:`EvasionAction.ADD_DELAY`
          3rd block  → :attr:`EvasionAction.CHANGE_ENCODING`
          4th block  → :attr:`EvasionAction.FRAGMENT_REQUEST`
          >max       → :attr:`EvasionAction.ABORT`

        Args:
            result: The :class:`WAFDetectionResult` from :meth:`detect`.

        Returns:
            The recommended :class:`EvasionAction`.
        """
        if not result.detected:
            return EvasionAction.NONE

        max_retries: int = self.config.get("max_retries", 3)
        if self._blocked_count > max_retries:
            self.log.error(
                f"WAF block limit exceeded ({self._blocked_count}/{max_retries}). "
                "Recommending ABORT."
            )
            return EvasionAction.ABORT

        if self._blocked_count == 1:
            action = EvasionAction.ROTATE_UA
        elif self._blocked_count == 2:
            action = EvasionAction.ADD_DELAY
        elif self._blocked_count == 3:
            action = EvasionAction.CHANGE_ENCODING
        else:
            action = EvasionAction.FRAGMENT_REQUEST

        self.log.info(
            f"WAF evasion recommendation: {action.value} "
            f"(block #{self._blocked_count})"
        )
        return action

    # ------------------------------------------------------------------
    # Evasion helpers
    # ------------------------------------------------------------------

    def get_evasion_headers(self) -> Dict[str, str]:
        """
        Generate HTTP headers that reduce WAF fingerprint detectability.

        Includes browser-like Accept/* headers, optional UA rotation, and
        cache-busting directives.

        Returns:
            Dict of HTTP headers ready to merge into a request.
        """
        from scanners.base_scanner import _USER_AGENTS

        headers: Dict[str, str] = {
            "Accept": (
                "text/html,application/xhtml+xml,application/xml;"
                "q=0.9,image/avif,image/webp,*/*;q=0.8"
            ),
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": random.choice(
                ["en-US,en;q=0.9", "en-GB,en;q=0.8", "fr-FR,fr;q=0.9,en;q=0.8"]
            ),
            "Connection": "keep-alive",
            "Cache-Control": "no-cache",
            "Pragma": "no-cache",
            "Upgrade-Insecure-Requests": "1",
        }

        if self.config.get("rotate_ua", True):
            headers["User-Agent"] = random.choice(_USER_AGENTS)

        return headers

    def encode_payload(self, payload: str, technique: str = "url") -> str:
        """
        Apply an encoding transformation to a payload string to evade
        signature-based pattern matching.

        Args:
            payload:   The raw payload string to transform.
            technique: One of ``'url'`` | ``'double_url'`` | ``'html'`` |
                       ``'unicode'`` | ``'case'``.

        Returns:
            The encoded payload string.
        """
        import urllib.parse

        if technique == "url":
            return urllib.parse.quote(payload, safe="")
        elif technique == "double_url":
            return urllib.parse.quote(urllib.parse.quote(payload, safe=""), safe="")
        elif technique == "html":
            return payload.replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
        elif technique == "unicode":
            # Replace ASCII letters with their unicode fullwidth equivalents
            encoded = ""
            for ch in payload:
                if "a" <= ch <= "z":
                    encoded += chr(ord(ch) - ord("a") + 0xFF41)
                elif "A" <= ch <= "Z":
                    encoded += chr(ord(ch) - ord("A") + 0xFF21)
                else:
                    encoded += ch
            return encoded
        elif technique == "case":
            # Mixed-case to defeat case-sensitive signatures
            result = ""
            for i, ch in enumerate(payload):
                result += ch.upper() if i % 2 == 0 else ch.lower()
            return result
        else:
            self.log.warning(f"Unknown encoding technique {technique!r}; returning original")
            return payload

    def get_delay(self) -> float:
        """
        Return a randomised delay in seconds appropriate for the current profile.

        Returns:
            Float delay in seconds.
        """
        lo, hi = self.config.get("delay_range", (0.5, 1.5))
        return random.uniform(lo, hi)

    @property
    def blocked_count(self) -> int:
        """Total number of WAF blocks detected in this session."""
        return self._blocked_count

    @property
    def detected_vendor(self) -> Optional[str]:
        """Name of the last identified WAF vendor, or ``None``."""
        return self._detected_vendor

    def reset(self) -> None:
        """
        Reset block counter and vendor state.

        Call between distinct scan targets if the same :class:`WAFEvasion`
        instance is reused.
        """
        self._blocked_count = 0
        self._detected_vendor = None
        self._successful_technique = None
        self.log.debug("WAFEvasion state reset")

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"WAFEvasion(profile={self.profile!r}, "
            f"blocked={self._blocked_count}, "
            f"vendor={self._detected_vendor!r})"
        )
